### ISSUE TITLE
Can not run example

### ISSUE THREAD

**Issue by Tetsujinfr** [jswulff/mrflow#1]
Hi, first thanks for your work ad for sharing it.

I am trying to execute your example but I have the following error message. It seems it may relate to the env variable but I think I did export it properly. Can you help?below the shell outputs when executing:

```
tets:~/mrflow-master$ sudo python mrflow.py --no_init example/frame1.png example/frame2.png example/frame3.png
Traceback (most recent call last):
  File "mrflow.py", line 11, in <module>
    MRFLOW_HOME = os.environ['MRFLOW_HOME']
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'MRFLOW_HOME'
tets:~/mrflow-master$ $MRFLOW_HOME/
bash: /home/tets/mrflow-master/: Is a directory
```

Tets

**Comment by Tetsujinfr** [comment]
Above output is what I get when running the instruction "sudo python mrflow.py --no_init example/frame1.png example/frame2.png example/frame3.png".
Now if I run without sudo, i.e. simply "python mrflow.py --no_init example/frame1.png example/frame2.png example/frame3.png", I got a longer output but still an error:

```
tets:~/mrflow-master$ python mrflow.py --no_init example/frame1.png example/frame2.png example/frame3.png
=== ARGUMENTS ===
	 alignment_error_type 	 : 	 3
	 alignment_ransac 	 : 	 0
	 alignment_ransac_threshold 	 : 	 2.0
	 backflow_bwd 	 : 	 
	 backflow_fwd 	 : 	 
	 debug 	 : 	 2
	 debug_compute_figure 	 : 	 0
	 debug_save_frames 	 : 	 0
	 debug_use_rigidity_gt 	 : 	 0
	 feature_sampling 	 : 	 10
	 featurelocations_nms 	 : 	 0
	 flow_bwd 	 : 	 
	 flow_fwd 	 : 	 
	 flow_fwd_gt 	 : 	 
	 frame0 	 : 	 example/frame1.png
	 frame1 	 : 	 example/frame2.png
	 frame2 	 : 	 example/frame3.png
	 no_init 	 : 	 True
	 nonlinear_structure_initialization 	 : 	 1
	 occlusion_reasoning 	 : 	 1
	 occlusion_threshold 	 : 	 2.0
	 override_optimization 	 : 	 0
	 refine_coplanarity 	 : 	 1
	 rigidity 	 : 	 
	 rigidity_gt 	 : 	 
	 rigidity_sigma_direction 	 : 	 1.0
	 rigidity_sigma_structure 	 : 	 1.0
	 rigidity_use_structure 	 : 	 1
	 rigidity_weight_cnn 	 : 	 0.0
	 scale_structure 	 : 	 1
	 tempdir 	 : 	 .
	 use_klt 	 : 	 0
	 variational_N_inner 	 : 	 1
	 variational_N_outer 	 : 	 5
	 variational_N_scales 	 : 	 1
	 variational_dataterm_grayscale 	 : 	 1
	 variational_lambda_1storder 	 : 	 0.5
	 variational_lambda_2ndorder 	 : 	 5.0
	 variational_lambda_consistency 	 : 	 0.0
	 variational_last_scale 	 : 	 0
	 variational_min_weight 	 : 	 0.0
	 variational_scale_factor 	 : 	 0.5
=================
(MM) PATHS:
(MM)	 path_backflow_bwd: 
(MM)	 path_backflow_fwd: 
(MM)	 path_flow_bwd: 
(MM)	 path_flow_fwd: 
(MM)	 path_flow_fwd_gt: 
(MM)	 path_image_current: example/frame2.png
(MM)	 path_image_next: example/frame3.png
(MM)	 path_image_prev: example/frame1.png
(MM)	 path_rigidity: 
(MM)	 path_rigidity_gt: 
Computing flow fields... 
(EE) Exception in load_data.py
Traceback (most recent call last):
  File "/home/tets/mrflow-master/load_data.py", line 94, in load_initial_data
    D = cv2.optflow.createOptFlow_DeepFlow()
AttributeError: 'module' object has no attribute 'optflow'
Traceback (most recent call last):
  File "mrflow.py", line 378, in <module>
    main()
  File "mrflow.py", line 374, in main
    compute_mrflow(paths,args)
  File "mrflow.py", line 43, in compute_mrflow
    data_in = load_data.load_initial_data(params=params, **paths)
  File "/home/tets/mrflow-master/load_data.py", line 235, in load_initial_data
    flow_fwd = epicwrapper.compute_epicflow(
AttributeError: 'NoneType' object has no attribute 'compute_epicflow'
```

Can you help please ?
thanks
tets

**Comment by jswulff** [comment]
Hi Tets,

The reason for your error is that you don't seem to have a current version of the opencv_contrib (https://github.com/opencv/opencv_contrib) packages installed.

If you want to use MR-Flow without initialization, the initial flow is computed using DeepFlow, which is included in the opencv_contrib package (but not in the basic OpenCV install).

Hope this helps.

**Comment by Tetsujinfr** [comment]
thanks. Indeed, I forgot to connect properly to my opencv 3 environment. So I did it and the demo started running for about 15 seconds doing mainy steps, but I got a new error at some point.
The first error msg is "TRWS code not found.", but I have no idea on what this means and could not find much on google on this.
I attach the output log below, any idea on what went wrong?

```
python mrflow.py --no_init example/frame1.png example/frame2.png example/frame3.png
=== ARGUMENTS ===
	 alignment_error_type 	 : 	 3
	 alignment_ransac 	 : 	 0
	 alignment_ransac_threshold 	 : 	 2.0
	 backflow_bwd 	 : 	 
	 backflow_fwd 	 : 	 
	 debug 	 : 	 2
	 debug_compute_figure 	 : 	 0
	 debug_save_frames 	 : 	 0
	 debug_use_rigidity_gt 	 : 	 0
	 feature_sampling 	 : 	 10
	 featurelocations_nms 	 : 	 0
	 flow_bwd 	 : 	 
	 flow_fwd 	 : 	 
	 flow_fwd_gt 	 : 	 
	 frame0 	 : 	 example/frame1.png
	 frame1 	 : 	 example/frame2.png
	 frame2 	 : 	 example/frame3.png
	 no_init 	 : 	 True
	 nonlinear_structure_initialization 	 : 	 1
	 occlusion_reasoning 	 : 	 1
	 occlusion_threshold 	 : 	 2.0
	 override_optimization 	 : 	 0
	 refine_coplanarity 	 : 	 1
	 rigidity 	 : 	 
	 rigidity_gt 	 : 	 
	 rigidity_sigma_direction 	 : 	 1.0
	 rigidity_sigma_structure 	 : 	 1.0
	 rigidity_use_structure 	 : 	 1
	 rigidity_weight_cnn 	 : 	 0.0
	 scale_structure 	 : 	 1
	 tempdir 	 : 	 .
	 use_klt 	 : 	 0
	 variational_N_inner 	 : 	 1
	 variational_N_outer 	 : 	 5
	 variational_N_scales 	 : 	 1
	 variational_dataterm_grayscale 	 : 	 1
	 variational_lambda_1storder 	 : 	 0.5
	 variational_lambda_2ndorder 	 : 	 5.0
	 variational_lambda_consistency 	 : 	 0.0
	 variational_last_scale 	 : 	 0
	 variational_min_weight 	 : 	 0.0
	 variational_scale_factor 	 : 	 0.5
=================
(MM) PATHS:
(MM)	 path_backflow_bwd: 
(MM)	 path_backflow_fwd: 
(MM)	 path_flow_bwd: 
(MM)	 path_flow_fwd: 
(MM)	 path_flow_fwd_gt: 
(MM)	 path_image_current: example/frame2.png
(MM)	 path_image_next: example/frame3.png
(MM)	 path_image_prev: example/frame1.png
(MM)	 path_rigidity: 
(MM)	 path_rigidity_gt: 
Computing flow fields... 
	fwd
	bwd
	backflow, fwd
	backflow, bwd
FundmatFilter: Removing 581 of 4011 features.
FundmatFilter: Removing 702 of 4011 features.
Number of all frame matches: 3135
Matches in frame 0: 3430
Matches in frame 1: 3309
(3135, 2, 3)
[RANSAC] Running RANSAC for a maximum of 10000 iterations.
[RANSAC] Done looping. 9975 of 10000 attempts were successful.
(MM) Number of inliers: 3135
[RANSAC] Running RANSAC for a maximum of 10000 iterations.
[RANSAC] Done looping. 3326 of 10000 attempts were successful.
(MM) 1373 of 3135 points are inliers according to H.
(MM) Points to use: 
[[ 380.  410.    1.]
 [ 150.   90.    1.]
 [ 930.  190.    1.]]
Initial EP 0: [ 5870.57868487 -2421.2653024 ] 
Initial EP 2 0: [-6695.38340892  2101.83295706]
Initial H 0
[[  1.02396599e+00   4.37729658e-02  -1.84905983e+01]
 [ -3.85600811e-03   9.91797698e-01   3.67375722e+00]
 [  1.12794511e-05  -8.07382288e-06   1.00000000e+00]]
Initial EP 1: [-7313.69350616  3295.50634786] 
Initial EP 2 1: [-6882.85678268  2085.20386994]
Initial H 1
[[  9.76940263e-01  -4.30556401e-02   1.82507540e+01]
 [  3.96857809e-03   1.00857114e+00  -3.69916298e+00]
 [ -1.06112378e-05   8.90035820e-06   1.00000000e+00]]
--- Mcor ---
[[  3.59764511e-02   7.79259231e-03   4.92641843e-05]
 [  7.79259231e-03   2.12118868e-02   2.11904364e-05]
 [  4.92641843e-05   2.11904364e-05   2.74273500e-05]]
---
(MM) Initialization: Refining homographies...
(MM) Initialization: Refinement took 10.3682560921 seconds
-- Initial homography for frame 0 --
[[  1.02396599e+00   4.37729658e-02  -1.84905983e+01]
 [ -3.85600811e-03   9.91797698e-01   3.67375722e+00]
 [  1.12794511e-05  -8.07382288e-06   1.00000000e+00]]
-- Initial homography for frame 1 --
[[  9.76940263e-01  -4.30556401e-02   1.82507540e+01]
 [  3.96857809e-03   1.00857114e+00  -3.69916298e+00]
 [ -1.06112378e-05   8.90035820e-06   1.00000000e+00]]
--- Epipoles after refinement: ---
[-6366.34035706  1997.80277315]
[-8494.26623056  2537.42623482]
-- Refined homography for frame 0 --
[[  1.02380796e+00   4.36303305e-02  -1.84659153e+01]
 [ -3.86862078e-03   9.91729988e-01   3.66988063e+00]
 [  1.11845530e-05  -8.34794090e-06   1.00000000e+00]]
-- Refined homography for frame 1 --
[[  9.76833861e-01  -4.32945834e-02   1.83223079e+01]
 [  3.94189881e-03   1.00826580e+00  -3.63682775e+00]
 [ -1.06262776e-05   8.51015325e-06   1.00000000e+00]]
Q old: [-6366.34035706  1997.80277315]
Q new: [-6366.34035706  1997.80277315]
Q old: [-8494.26623056  2537.42623482]
Q new: [-8494.26623056  2537.42623482]
========== Refining backwards motion and structure ==========
--- sigma = 0.0205711447267 ---
--- Median error = -0.00984608683298 ---
--- Median abs error = 0.0230837616107 ---
	Scale 16, Q: Optimization took 0.302081108093 seconds
		 q: [-6366.34035706  1997.80277315] => [-6498.36348909  1446.22937022]
--- sigma = 0.0204213247047 ---
--- Median error = -0.00876064162174 ---
--- Median abs error = 0.0225255344029 ---
	Scale 16: Optimization took 2.58226394653 seconds
--- sigma = 0.0193462602807 ---
--- Median error = -0.00394367174937 ---
--- Median abs error = 0.0196996733565 ---
	Scale 8, Q: Optimization took 0.175444126129 seconds
		 q: [-6498.36348909  1446.22937022] => [-6493.46030454  1526.98151266]
--- sigma = 0.0191521571053 ---
--- Median error = -0.00381856700872 ---
--- Median abs error = 0.0195437735644 ---
	Scale 8: Optimization took 1.00012397766 seconds
--- sigma = 0.0191233484395 ---
--- Median error = -0.00212798865868 ---
--- Median abs error = 0.0193021282596 ---
	Scale 4, Q: Optimization took 0.20831489563 seconds
		 q: [-6493.46030454  1526.98151266] => [-6484.99276739  1581.33905587]
--- sigma = 0.0190019384288 ---
--- Median error = -0.00217480846437 ---
--- Median abs error = 0.019156546757 ---
	Scale 4: Optimization took 1.06375408173 seconds
--- sigma = 0.018893015531 ---
--- Median error = -0.00113343943666 ---
--- Median abs error = 0.018993714673 ---
	Scale 2, Q: Optimization took 0.734215021133 seconds
		 q: [-6484.99276739  1581.33905587] => [-6475.01344309  1627.6634493 ]
--- sigma = 0.0187057795878 ---
--- Median error = -0.00121494862134 ---
--- Median abs error = 0.0188120695372 ---
	Scale 2: Optimization took 1.70623588562 seconds
====== Refinement results ======
Backward:
B:	-5.13068659848	=>	-5.1290570427
H:
[[  1.02380796e+00   4.36303305e-02  -1.84659153e+01]
 [ -3.86862078e-03   9.91729988e-01   3.66988063e+00]
 [  1.11845530e-05  -8.34794090e-06   1.00000000e+00]]
-
[[  1.02350890e+00   4.29626959e-02  -1.81821610e+01]
 [ -3.98065478e-03   9.86700860e-01   4.80642305e+00]
 [  1.08322385e-05  -7.84082502e-06   1.00000000e+00]]

Forward:
B:	3.90751767234	=>	3.90751767234
H:
[[  9.76833861e-01  -4.32945834e-02   1.83223079e+01]
 [  3.94189881e-03   1.00826580e+00  -3.63682775e+00]
 [ -1.06262776e-05   8.51015325e-06   1.00000000e+00]]
-
[[  9.76833861e-01  -4.32945834e-02   1.83223079e+01]
 [  3.94189881e-03   1.00826580e+00  -3.63682775e+00]
 [ -1.06262776e-05   8.51015325e-06   1.00000000e+00]]


(MM) Mean/Median of structure difference before optimization: 0.174015687353	0.034384004267
(MM) Mean/Median of structure difference after backward optimization: 0.174192843049	0.0280497212624
(MM) Mean/Median of structure difference after forward optimization: 0.174192843049	0.0280497212624
========== Refining rigidity map ==========
********************************************************************************
(EE) TRWS code not found.
********************************************************************************
==== EXCEPTION ====
Traceback (most recent call last):
  File "mrflow.py", line 111, in compute_mrflow
    params)
  File "/home/tets/mrflow-master/pipeline/compute_structure.py", line 397, in compute_structure
    rigidity_refined = inference.infer_mrf(images[1], unaries, lambd=LAMBD)
  File "/home/tets/mrflow-master/rigidity/inference.py", line 106, in infer_mrf
    sys.exit(0)
SystemExit: 0

```

**Comment by Tetsujinfr** [comment]
Ok ,so after my earlier struggle I ended up forgetting about compiling TRWS as mentioned in the readme. I am trying to compile it now and then I should be ok. I got some compiling error right now but I will hopefully success soon.

**Comment by Tetsujinfr** [comment]
Ok so I really struggled to compile TRWS with Cython. Now after googling the error message I was getting, it turned out that Cython does not like "-" characters, and I did not change the default zip folder name of MrFlow git which was "mrflow-master" ....
So after renaming the main folder name into "mrflow" instead of "mrflow-master", then a "sudo ./build_trws" did work fine.

So for newbies like me, be careful with folder names containing "-" when using Cython compilation!

**Comment by jswulff** [comment]
Hi Tets,

Thanks for pointing this out -- the bug is fixed now, and it should not matter anymore what the directory name is.

-Jonas
